
export const ProductInfo = [
  {
    id: 1,
    //product_name: "Avocado",
    description: "Creamy",
    price: "$4.00 ",
    image: require("./Assets/images/avocado.jpg"),
  },
  {
    id: 2,
    product_name: "Banana Pudding",
    description: "Creamy",
    price: "$4.00",
    image: require("./Assets/images/bananaPudding.jpg"),
  },
  {
    id: 3,
    product_name: "Brownie",
    description: "Creamy",
    price: "$4.00",
    image: require("./Assets/images/brownie.jpg"),
  },

  {
    id: 4,
    product_name: "Caramel Kiss",
    description: "Creamy",
    price: "$4.00",
    image: require("./Assets/images/caramelKiss.jpg"),
  },
  {
    id: 5,
    product_name: "Cherry Mascarpone",
    description: "Creamy",
    price: "$4.00",
    image: require("./Assets/images/cherryMascarpone.jpg"),
  },
  {
    id: 6,
    product_name: "Cuban Wake Up",
    description: "Creamy- Caffine",
    price: "$4.00",
    image:require ("./Assets/images/cubanWakeUp.jpg"),
  },
  {
    id: 7,
    product_name: "Desperado",
    description: "Creamy -Caffine",
    price: "$4.00",
    image: require ("./Assets/images/desperado.jpg"),
  },
  {
    id: 8,
    product_name: "grape",
    description: "Fruity",
    price: "$4.00",
    image: require ("./Assets/images/grape.jpg"),
  },
  {
    id: 9,
    product_name: "Lemon Zest",
    description: "Fruity",
    price: "$4.00",
    image: require ("./Assets/images/lemonZest.jpg"),
  },

  {
    id: 10,
    product_name: "mangoGinger",
    description: "Fruity",
    price: "$4.00",
    image: require ("./Assets/images/mangoGinger.jpg"),
  },
  {
    id: 11,
    product_name: "mocha",
    description: "Creamy- Caffine",
    price: "$4.00",
    image: require ("./Assets/images/mocha.jpg"),
  },
  {
    id: 12,
    product_name: "Peach Pineapple",
    description: "Fruity",
    price: "$4.00",
    image: require ("./Assets/images/peachPineapple.jpg"),
  },
  {
    id: 13,
    product_name: "Italian Grapefruit",
    description: "Fruity",
    price: "$4.00",
    image: require ("./Assets/images/italianGrapeFruit.jpg"),
  },
  {
    id: 14,
    product_name: "Strawberry ShortCake",
    description: "Creamy",
    price: "$4.00",
    image: require  ("./Assets/images/strawberryShortCake.jpg"),
  },
  {
    id: 15,
    product_name: "Vegan Strawberry",
    description: "Fruity",
    price: "$4.00",
    image: require ("./Assets/images/veganStrawberry.jpg"),
  },
  // {
  //   id: 16,
  //   product_name: "White Mocha",
  //   description: "Creamy",
  //   price: "$4.00",
  //   image: require ("./Assets/images/whiteMocha.jpg"),
  // },
  // {
  //   id: 17,
  //   product_name: "Caramel Kiss",
  //   description: "Creamy",
  //   price: "$4.00",
  //   image: require("./Assets/images/caramelKiss.jpg"),
  // },
  // {
  //   id: 18,
  //   product_name: "White Mocha",
  //   description: "Creamy",
  //   price: "$4.00",
  //   image: require ("./Assets/images/whiteMocha.jpg"),
  // },
];
